// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const GlyphDigitalZionInner: typeof import('~icons/glyph/digital-zion-inner.jsx')['default']
  const GlyphDigitalZionOuter: typeof import('~icons/glyph/digital-zion-outer.jsx')['default']
  const Icon400Million: typeof import('~icons/icon/400-million.jsx')['default']
  const IconOpenCollective: typeof import('~icons/icon/open-collective.jsx')['default']
  const MdiGithub: typeof import('~icons/mdi/github.jsx')['default']
}
export {}
